# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Garrett Webb
title: Computer Science Student at UCSC
email: garrettwebb97@gmail.com
website: https://Garrett-Webb.github.io

# Social links
twitter_username: facespics
github_username:  Garrett-Webb
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: garrettwebb97
linkedin_username: Garrett Webb
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Garrett and I'm a Student at University of California, Santa Cruz. I worked as an Information Systems Specialist, and as a Systems Engineering Intern for Aerovironment Inc.

  I am most skilled in: <mark>C/C++</mark> and <mark>System Architecture</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering, some of my other interests and hobbies are:
   - Underwater Basket Weaving
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
